import json
import os

files = ['en.json', 'hi.json', 'gu.json']
dir_path = 'client/messages'

en_home = {
  "loading": "Loading…",
  "heroTitle1": "Find Your Perfect",
  "heroTitle2": "Opportunity Today",
  "heroDesc": "Connect talented workers with amazing opportunities. Build your career with India's most trusted work platform.",
  "findJobs": "Find Jobs",
  "dashboard": "Dashboard",
  "getStarted": "Get Started",
  "signIn": "Sign In",
  "activeUsers": "Active Users",
  "jobsPosted": "Jobs Posted",
  "avgRating": "Avg Rating",
  "whyChoose": "Why Choose VaaniKaam?",
  "quickApply": "Quick Apply",
  "quickApplyDesc": "Apply in seconds with your verified profile",
  "verifiedWorkers": "Verified Workers",
  "verifiedWorkersDesc": "All workers pass background verification",
  "support": "24/7 Support",
  "supportDesc": "Round-the-clock support for every query",
  "ratingsReviews": "Ratings & Reviews",
  "ratingsReviewsDesc": "Build reputation with genuine client reviews",
  "popularJobs": "Popular Jobs Near You",
  "popularJobsDesc": "Opportunities matched to your location",
  "viewJob": "View Job",
  "viewAllJobs": "View All Jobs",
  "howItWorks": "How It Works",
  "createProfile": "Create Profile",
  "createProfileDesc": "Sign up in minutes",
  "browseJobs": "Browse Jobs",
  "browseJobsDesc": "Find matching opportunities",
  "applyInstantly": "Apply Instantly",
  "applyInstantlyDesc": "One-tap job applications",
  "getHired": "Get Hired",
  "getHiredDesc": "Start earning right away",
  "manageContracts": "Manage Your Contracts",
  "manageContractsDesc": "Track active projects and earnings",
  "activeContracts": "Active Contracts",
  "viewAll": "View All",
  "totalEarnings": "Total Earnings",
  "withdraw": "Withdraw",
  "pendingProjects": "Pending Projects",
  "review": "Review",
  "completionRate": "Completion Rate",
  "averageRating": "Average Rating",
  "totalProjects": "Total Projects",
  "responseTime": "Response Time",
  "yourWorkStats": "Your Work Stats",
  "yourWorkStatsDesc": "Track your progress and opportunities",
  "jobApplications": "Job Applications",
  "history": "History",
  "profileViews": "Profile Views",
  "updateProfile": "Update Profile",
  "jobsCompleted": "Jobs Completed",
  "onTimeRate": "On-time Rate",
  "repeatClients": "Repeat Clients",
  "avgResponse": "Avg Response",
  "trendingCategories": "Trending Categories",
  "active": "Active",
  "thisMonth": "This Month",
  "pending": "Pending",
  "total": "Total",
  "plumbing": "Plumbing",
  "construction": "Construction",
  "cleaning": "Cleaning",
  "painting": "Painting",
  "electrical": "Electrical",
  "carpentry": "Carpentry",
  "footerTagline": "Empowering workers and businesses across India",
  "footerAbout": "About",
  "footerTerms": "Terms",
  "footerPrivacy": "Privacy",
  "footerCopyright": "© 2026 VaaniKaam. All rights reserved."
}

hi_home = {
  "loading": "लोड हो रहा है…",
  "heroTitle1": "अपना आदर्श काम",
  "heroTitle2": "आज ही खोजें",
  "heroDesc": "प्रतिभाशाली श्रमिकों को अद्भुत अवसरों से जोड़ें। भारत के सबसे भरोसेमंद वर्क प्लेटफॉर्म के साथ अपना करियर बनाएं।",
  "findJobs": "नौकरियां खोजें",
  "dashboard": "डैशबोर्ड",
  "getStarted": "शुरू करें",
  "signIn": "साइन इन करें",
  "activeUsers": "सक्रिय उपयोगकर्ता",
  "jobsPosted": "नौकरियां पोस्ट की गईं",
  "avgRating": "औसत रेटिंग",
  "whyChoose": "VaaniKaam क्यों चुनें?",
  "quickApply": "त्वरित आवेदन",
  "quickApplyDesc": "अपने सत्यापित प्रोफ़ाइल के साथ सेकंड में आवेदन करें",
  "verifiedWorkers": "सत्यापित श्रमिक",
  "verifiedWorkersDesc": "सभी श्रमिक पृष्ठभूमि सत्यापन पास करते हैं",
  "support": "24/7 सहायता",
  "supportDesc": "हर प्रश्न के लिए चौबीसों घंटे सहायता",
  "ratingsReviews": "रेटिंग और समीक्षाएं",
  "ratingsReviewsDesc": "वास्तविक ग्राहक समीक्षाओं के साथ प्रतिष्ठा बनाएं",
  "popularJobs": "आपके आस-पास लोकप्रिय नौकरियां",
  "popularJobsDesc": "आपके स्थान से मेल खाते अवसर",
  "viewJob": "नौकरी देखें",
  "viewAllJobs": "सभी नौकरियां देखें",
  "howItWorks": "यह कैसे काम करता है",
  "createProfile": "प्रोफ़ाइल बनाएं",
  "createProfileDesc": "मिनटों में साइन अप करें",
  "browseJobs": "नौकरियां ब्राउज़ करें",
  "browseJobsDesc": "मेल खाने वाले अवसर खोजें",
  "applyInstantly": "तुरंत आवेदन करें",
  "applyInstantlyDesc": "एक-टैप नौकरी आवेदन",
  "getHired": "काम पर रखें जाएं",
  "getHiredDesc": "तुरंत कमाई शुरू करें",
  "manageContracts": "अपने अनुबंध प्रबंधित करें",
  "manageContractsDesc": "सक्रिय परियोजनाओं और कमाई को ट्रैक करें",
  "activeContracts": "सक्रिय अनुबंध",
  "viewAll": "सभी देखें",
  "totalEarnings": "कुल कमाई",
  "withdraw": "पैसे निकालें",
  "pendingProjects": "लंबित परियोजनाएं",
  "review": "समीक्षा करें",
  "completionRate": "पूरा करने की दर",
  "averageRating": "औसत रेटिंग",
  "totalProjects": "कुल परियोजनाएं",
  "responseTime": "प्रतिक्रिया समय",
  "yourWorkStats": "आपके काम के आँकड़े",
  "yourWorkStatsDesc": "अपनी प्रगति और अवसरों को ट्रैक करें",
  "jobApplications": "नौकरी आवेदन",
  "history": "इतिहास",
  "profileViews": "प्रोफ़ाइल दृश्य",
  "updateProfile": "प्रोफ़ाइल अपडेट करें",
  "jobsCompleted": "नौकरियां पूरी कीं",
  "onTimeRate": "समय पर दर",
  "repeatClients": "दोहराए जाने वाले ग्राहक",
  "avgResponse": "औसत प्रतिक्रिया",
  "trendingCategories": "ट्रेंडिंग श्रेणियां",
  "active": "सक्रिय",
  "thisMonth": "इस महीने",
  "pending": "लंबित",
  "total": "कुल",
  "plumbing": "प्लंबिंग",
  "construction": "निर्माण",
  "cleaning": "सफाई",
  "painting": "पेंटिंग",
  "electrical": "इलेक्ट्रिकल",
  "carpentry": "बढ़ईगिरी",
  "footerTagline": "पूरे भारत में श्रमिकों और व्यवसायों को सशक्त बनाना",
  "footerAbout": "हमारे बारे में",
  "footerTerms": "शर्तें",
  "footerPrivacy": "गोपनीयता",
  "footerCopyright": "© 2026 VaaniKaam. सर्वाधिकार सुरक्षित।"
}

gu_home = {
  "loading": "લોડ થઈ રહ્યું છે…",
  "heroTitle1": "તમારું આદર્શ કામ",
  "heroTitle2": "આજે જ શોધો",
  "heroDesc": "પ્રતિભાશાળી કામદારોને અદ્ભુત તકો સાથે જોડો. ભારતની સૌથી વિશ્વસનીય વર્ક પ્લેટફોર્મ સાથે તમારી કારકિર્દી બનાવો.",
  "findJobs": "નોકરીઓ શોધો",
  "dashboard": "ડેશબોર્ડ",
  "getStarted": "શરૂ કરો",
  "signIn": "સાઇન ઇન કરો",
  "activeUsers": "સક્રિય વપરાશકર્તાઓ",
  "jobsPosted": "પોસ્ટ કરેલી નોકરીઓ",
  "avgRating": "સરેરાશ રેટિંગ",
  "whyChoose": "VaaniKaam શા માટે પસંદ કરવું?",
  "quickApply": "ઝડપી અરજી",
  "quickApplyDesc": "તમારી ચકાસાયેલ પ્રોફાઇલ સાથે સેકન્ડોમાં અરજી કરો",
  "verifiedWorkers": "ચકાસાયેલ કામદારો",
  "verifiedWorkersDesc": "તમામ કામદારો પૃષ્ઠભૂમિ ચકાસણી પાસ કરે છે",
  "support": "24/7 સપોર્ટ",
  "supportDesc": "દરેક પ્રશ્ન માટે ચોવીસ કલાક સપોર્ટ",
  "ratingsReviews": "રેટિંગ્સ અને સમીક્ષાઓ",
  "ratingsReviewsDesc": "વાસ્તવિક ગ્રાહક સમીક્ષાઓ સાથે પ્રતિષ્ઠા બનાવો",
  "popularJobs": "તમારી નજીકની લોકપ્રિય નોકરીઓ",
  "popularJobsDesc": "તમારા સ્થાન સાથે મેળ ખાતી તકો",
  "viewJob": "નોકરી જુઓ",
  "viewAllJobs": "બધી નોકરીઓ જુઓ",
  "howItWorks": "તે કેવી રીતે કામ કરે છે",
  "createProfile": "પ્રોફાઇલ બનાવો",
  "createProfileDesc": "મિનિટોમાં સાઇન અપ કરો",
  "browseJobs": "નોકરીઓ બ્રાઉઝ કરો",
  "browseJobsDesc": "મેળ ખાતી તકો શોધો",
  "applyInstantly": "તરત જ અરજી કરો",
  "applyInstantlyDesc": "એક-ટેપ નોકરી અરજી",
  "getHired": "નોકરી મેળવો",
  "getHiredDesc": "તરત જ કમાણી શરૂ કરો",
  "manageContracts": "તમારા કરારો મેનેજ કરો",
  "manageContractsDesc": "સક્રિય પ્રોજેક્ટ્સ અને કમાણીને ટ્રૅક કરો",
  "activeContracts": "સક્રિય કરારો",
  "viewAll": "બધું જુઓ",
  "totalEarnings": "કુલ કમાણી",
  "withdraw": "ઉપાડ",
  "pendingProjects": "બાકી પ્રોજેક્ટ્સ",
  "review": "સમીક્ષા કરો",
  "completionRate": "પૂર્ણતા દર",
  "averageRating": "સરેરાશ રેટિંગ",
  "totalProjects": "કુલ પ્રોજેક્ટ્સ",
  "responseTime": "પ્રતિભાવ સમય",
  "yourWorkStats": "તમારા કામના આંકડા",
  "yourWorkStatsDesc": "તમારી પ્રગતિ અને તકોને ટ્રૅક કરો",
  "jobApplications": "નોકરીની અરજીઓ",
  "history": "ઇતિહાસ",
  "profileViews": "પ્રોફાઇલ દૃશ્યો",
  "updateProfile": "પ્રોફાઇલ અપડેટ કરો",
  "jobsCompleted": "પૂર્ણ કરેલી નોકરીઓ",
  "onTimeRate": "સમય પર દર",
  "repeatClients": "પુનરાવર્તિત ગ્રાહકો",
  "avgResponse": "સરેરાશ પ્રતિભાવ",
  "trendingCategories": "ટ્રેન્ડિંગ શ્રેણીઓ",
  "active": "સક્રિય",
  "thisMonth": "આ મહિને",
  "pending": "બાકી",
  "total": "કુલ",
  "plumbing": "પ્લમ્બિંગ",
  "construction": "બાંધકામ",
  "cleaning": "સફાઈ",
  "painting": "પેઇન્ટિંગ",
  "electrical": "ઇલેક્ટ્રિકલ",
  "carpentry": "સુથારકામ",
  "footerTagline": "સમગ્ર ભારતમાં કામદારો અને વ્યવસાયોને સશક્તિકરણ",
  "footerAbout": "અમારા વિશે",
  "footerTerms": "શરતો",
  "footerPrivacy": "ગોપનીયતા",
  "footerCopyright": "© 2026 VaaniKaam. સર્વાધિકાર સુરક્ષિત."
}

dicts = {'en.json': en_home, 'hi.json': hi_home, 'gu.json': gu_home}
nav_texts = {
  'en.json': {"my-projects": "My Projects", "my-work": "My Work"},
  'hi.json': {"my-projects": "मेरे प्रोजेक्ट", "my-work": "मेरा काम"},
  'gu.json': {"my-projects": "મારા પ્રોજેક્ટ્સ", "my-work": "મારું કામ"}
}

for f in files:
    path = os.path.join(dir_path, f)
    with open(path, 'r', encoding='utf-8') as file:
        data = json.load(file)
    data['home'] = dicts[f]
    if 'nav' not in data:
        data['nav'] = {}
    data['nav'].update(nav_texts[f])
    with open(path, 'w', encoding='utf-8') as file:
        json.dump(data, file, ensure_ascii=False, indent=2)
